- name: VsCode
  category: editor
  identifier:
    id: Code.exe
    kind: Exe
    matching_strategy: Equals

- name: Spark
  category: messaging
  workspace: media
  identifier:
    id: Spark Desktop.exe
    kind: Exe
    matching_strategy: Equals

- name: Discord
  category: messaging
  workspace: media
  identifier:
    id: Discord.exe
    kind: Exe
    matching_strategy: Equals

- name: NordPass
  identifier:
    kind: Exe
    id: NordPass.exe
  float_identifiers:
    - kind: Exe
      id: NordPass.exe

- name: Keepass
  identifier:
    kind: Exe
    id: KeePassXC.exe
  float_identifiers:
    - kind: Exe
      id: KeePassXC.exe

- name: AutoHotkey
  identifier:
    kind: Exe
    id: AutoHotkey64.exe
  float_identifiers:
    - kind: Exe
      id: AutoHotkey64.exe

- name: pinentry
  identifier:
    kind: Exe
    id: pinentry.exe
  float_identifiers:
    - kind: Exe
      id: pinentry.exe

- name: Assetto
  identifier:
    kind: Exe
    id: "Content Manager.exe"
  float_identifiers:
    - kind: Exe
      id: "Content Manager.exe"
    - kind: Title
      id: Assetto Corsa

- name: PS3
  identifier:
    kind: Exe
    id: "rpcs3.exe"
  float_identifiers:
    - kind: Exe
      id: "rpcs3.exe"
